-- Atividade 02 ---

SELECT 
	B.CODIGO_CLIENTE,
	B.NOME,
	B.SOBRENOME,
	B.CIDADE,
	A.CODIGO_PEDIDO,
    A.DATA_PEDIDO,
    D.PRODUTO AS PRODUTO_COMPRADO,
    A.VALOR AS VALOR_DO_PEDIDO
	
FROM TB_PEDIDOS A

JOIN tb_CLIENTES B 
    ON A.CODIGO_CLIENTE = B.CODIGO_CLIENTE 
JOIN TB_ITENS C 
    ON C.CODIGO_PEDIDO = A.CODIGO_PEDIDO
JOIN tb_PRODUTOS D 
    ON D.CODIGO_PRODUTO = C.CODIGO_PRODUTO
	
WHERE B.CIDADE = 'SAO PAULO' ;