SELECT 
    A.CODIGO_PEDIDO,
    A.DATA_PEDIDO,
    D.PRODUTO,
    A.VALOR
FROM TB_PEDIDOS A
JOIN TB_ITENS C 
    ON C.codigo_pedido= A.CODIGO_PEDIDO
JOIN TB_PRODUTOS D 
    ON D.CODIGO_PRODUTO = C.CODIGO_PRODUTO
    JOIN TB_CLIENTES B 
    ON A.CODIGO_CLIENTE = B.CODIGO_CLIENTE 
WHERE B.CIDADE = 'SAO PAULO';
